repositories:
- name: kedacore
  url: https://kedacore.github.io/charts

commonLabels:
  purpose: keda
  group: web

releases:
  - name: keda
    namespace: web
    chart: kedacore/keda
    version: 2.4.0

  - name: keda-http
    # must be in the same namespace as the scaled resource
    namespace: web
    chart: kedacore/keda-add-ons-http
    version: 0.3.0
    disableValidationOnInstall: true
    disableValidation: true
    installed: true
    values:
      - interceptor:
          proxy:
            port: 80

  - name: frontend
    namespace: web
    chart: ./charts/frontend
    disableValidationOnInstall: true
    disableValidation: true
    installed: true
    values:
      - autoscaling:
          enabled: true
  
  - name: backend
    namespace: web
    chart: ./charts/backend
    disableValidationOnInstall: true
    disableValidation: true
    installed: true
    values:
      - autoscaling:
          enabled: true
  
